import org.gradle.internal.os.OperatingSystem

pluginManagement {
  repositories {
    mavenLocal()
    gradlePluginPortal()
    def frcHome = OperatingSystem.current().isWindows()
        ? new File(System.getenv('PUBLIC') ?: 'C:\\Users\\Public', 'wpilib/2026')
        : new File(System.getProperty('user.home'), 'wpilib/2026')
    maven { url new File(frcHome, 'maven') }
  }
}

rootProject.name = 'State-Space-Control'
